# Generated by Django 6.0.5 on 2026-06-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'In attesa'), ('processing', 'In lavorazione'), ('shipped', 'Spedito')], default='pending', help_text="Stato di avanzamento dell'ordine", max_length=20),
        ),
    ]
