# Generated by Django 6.0.5 on 2026-06-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('store_manager', 'Store Manager'), ('warehouse_worker', 'Warehouse Worker')], default='customer', help_text="Ruolo dell'utente all'interno dell'e-commerce", max_length=20),
        ),
    ]
